name: OpenDevOps-Cadvisor
description: |
  Open DevOps Cadvisor Catalog
version: 1.0.0
category: MONITOR
maintainer: open.devops@gmail.com
license: Apache 2
projectURL: https://github.com/open-devops/docker-cov-cadvisor
